// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registerUseCase

import (
	"context"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRegisterUseCase(gormDb *gorm.DB, ctx context.Context) IRegisterUseCase {
	iRegisterRepository := NewRegisterRepository(gormDb, ctx)
	iRegisterUseCase := NewRegisterUseCase(iRegisterRepository, gormDb, ctx)
	return iRegisterUseCase
}
